name: "Bump iOS Version"
on:
  push:
    branches: [main]
jobs:
  tests:
    name: "Bump Version"
    runs-on: macos-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yanamura/ios-bump-version@v1
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD
